var coreCircles = [
	{ "x_axis": 50, "y_axis": 200, "radius": 10, "color" : "white", "class" : "big", "label" : "Authorization", "id" : "auth"},
	{ "x_axis": 128.5, "y_axis": 200, "radius": 6, "color" : "white", "class" : "small", "label" : "Generate", "id" : "authgen"},
	{ "x_axis": 207, "y_axis": 200, "radius": 6, "color" : "white", "class" : "small", "label" : "QA", "id" : "authqa"},
	{ "x_axis": 170, "y_axis": 300, "radius": 6, "color" : "white", "class" : "small", "label" : "No Auth Req", "id" : "noauth", "type" : "horz"},
	{ "x_axis": 285.5, "y_axis": 200, "radius": 6, "color" : "white", "class" : "small", "label" : "Followup", "id" : "authfollowup"},
	{ "x_axis": 364, "y_axis": 200, "radius": 10, "color" : "white", "class" : "big", "label" : "Subpeona", "id" : "sub"},
	{ "x_axis": 405, "y_axis": 250, "radius": 6, "color" : "white", "class" : "small", "label" : "Prepay", "id" : "prepay", "type" : "horz"},
	{ "x_axis": 442.5, "y_axis": 200, "radius": 6, "color" : "white", "class" : "small", "label" : "Generate", "id" : "subgen"},
	{ "x_axis": 521, "y_axis": 200, "radius": 6, "color" : "white", "class" : "small", "label" : "QA", "id" : "subqa"},
	{ "x_axis": 599.5, "y_axis": 200, "radius": 6, "color" : "white", "class" : "small", "label" : "Followup", "id" : "subfollowup"},
	{ "x_axis": 678, "y_axis": 200, "radius": 10, "color" : "white", "class" : "big", "label" : "Received", "id" : "received"},
	{ "x_axis": 756.5, "y_axis": 200, "radius": 6, "color" : "white", "class" : "small", "label" : "Req Atty", "type" : "horz", "replace" : true},
	{ "x_axis": 835, "y_axis": 200, "radius": 10, "color" : "white", "class" : "big", "label" : "Processing", "id" : "processing"},
	{ "x_axis": 913.5, "y_axis": 200, "radius": 10, "color" : "white", "class" : "big", "label" : "QA", "id" : "qa"},
	{ "x_axis": 992, "y_axis": 200, "radius": 10, "color" : "white", "class" : "big", "label" : "Billing", "id" : "billing"},
	{ "x_axis": 1070.5, "y_axis": 200, "radius": 10, "color" : "white", "class" : "big", "label" : "Finalize", "id" : "finalize"},
	{ "x_axis": 1150, "y_axis": 200, "radius": 10, "color" : "white", "class" : "big", "label" : "Complete", "id" : "complete"},
];